/*
 * Copyright (C) 2017-2024 Dominic Heutelbeck (dominic@heutelbeck.com)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * SAPL generated by Xtext
 */
package io.sapl.grammar.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class SAPLQuickfixProvider extends DefaultQuickfixProvider {

    // @Fix(SAPLValidator.INVALID_NAME)
    // public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
    // acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
    // public void apply(IModificationContext context) throws BadLocationException {
    // IXtextDocument xtextDocument = context.getXtextDocument();
    // String firstLetter = xtextDocument.get(issue.getOffset(), 1);
    // xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
    // }
    // });
    // }

}
