/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SAPLTestScopeProvider extends AbstractSAPLTestScopeProvider {

}
