<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2017-2023 Dominic Heutelbeck (dominic@heutelbeck.com)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sapl" nsURI="https://sapl.io/sapl/SAPL" nsPrefix="sapl">
  <eClassifiers xsi:type="ecore:EClass" name="SAPL" eSuperTypes="#//Matchable #//EvaluableDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
            eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyElement" eType="#//PolicyElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libSteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyElement" eSuperTypes="#//Matchable #//EvaluableDocument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="saplName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetExpression" eType="#//Expression"
          containment="true"/>
    </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schemaExpression" eType="#//Expression"
         containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscriptionElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicySet" eSuperTypes="#//PolicyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" eType="#//CombiningAlgorithm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueDefinitions" upperBound="-1"
        eType="#//ValueDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//Policy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy" eSuperTypes="#//PolicyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitlement" eType="#//Entitlement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//PolicyBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obligations" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advice" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entitlement" abstract="true" interface="true">
    <eOperations name="getDecision" lowerBound="1" eType="#//Decision">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permit" eSuperTypes="#//Entitlement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deny" eSuperTypes="#//Entitlement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyBody" eSuperTypes="#//Evaluable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueDefinition" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eval" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemaVarExpression" upperBound="-1" eType="#//Expression"
            containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Evaluable"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//FilterComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtemplate" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicRelative" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step">
    <eOperations name="apply" lowerBound="1" eType="#//ValFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
      <eParameters name="parentValue" eType="#//Val"/>
    </eOperations>
    <eOperations name="applyFilterStatement" lowerBound="1" eType="#//ValFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
      <eParameters name="parentValue" eType="#//Val"/>
      <eParameters name="stepId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="statement" eType="#//FilterStatement"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionStep" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Evaluable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterComponent">
    <eOperations name="apply" lowerBound="1" eType="#//ValFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
      <eParameters name="unfilteredRootNode" eType="#//Val"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="each" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//BasicRelative"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fsteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardImport" eSuperTypes="#//Import"/>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libAlias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperator" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperator" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOr" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EagerOr" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multi" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modulo" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EagerAnd" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotEquals" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Regex" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Less" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessEquals" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="More" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoreEquals" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementOf" eSuperTypes="#//BinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//UnaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryMinus" eSuperTypes="#//UnaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryPlus" eSuperTypes="#//UnaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicGroup" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicValue" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFunction" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fsteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicIdentifier" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEnvironmentAttribute" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEnvironmentHeadAttribute" eSuperTypes="#//BasicExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EscapedKeyStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardStep" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeFinderStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeadAttributeFinderStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecursiveKeyStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecursiveWildcardStep" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecursiveIndexStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArraySlicingStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexUnionStep" eSuperTypes="#//UnionStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indices" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeUnionStep" eSuperTypes="#//UnionStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Pair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueLiteral" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseLiteral" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="UndefinedLiteral" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterSimple" eSuperTypes="#//FilterComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="each" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fsteps" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//Arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterExtended" eSuperTypes="#//FilterComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//FilterStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluable" abstract="true" interface="true">
    <eOperations name="evaluate" lowerBound="1" eType="#//ValFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matchable" abstract="true" interface="true">
    <eOperations name="matches" eType="#//ValMono">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluableDocument" abstract="true" interface="true">
    <eOperations name="evaluate" lowerBound="1" eType="#//DocumentEvaluationResultFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="targetResult" lowerBound="1" eType="#//DocumentEvaluationResult">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
      <eParameters name="targetValue" eType="#//Val"/>
    </eOperations>
    <eOperations name="importError" lowerBound="1" eType="#//DocumentEvaluationResult">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
      <eParameters name="errorMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JsonNode" instanceClassName="com.fasterxml.jackson.databind.JsonNode"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JsonNodeFlux" instanceTypeName="reactor.core.publisher.Flux&lt;com.fasterxml.jackson.databind.JsonNode>"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuthorizationDecisionFlux" instanceTypeName="reactor.core.publisher.Flux&lt;io.sapl.api.pdp.AuthorizationDecision>"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DecisionFlux" instanceTypeName="reactor.core.publisher.Flux&lt;io.sapl.api.pdp.Decision>"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PolicyEvaluationException" instanceClassName="io.sapl.api.interpreter.PolicyEvaluationException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="StringMap" instanceTypeName="java.util.Map&lt;java.lang.String, java.lang.String>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ValFlux" instanceTypeName="reactor.core.publisher.Flux&lt;io.sapl.api.interpreter.Val>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanMono" instanceTypeName="reactor.core.publisher.Mono&lt;java.lang.Boolean>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Val" instanceClassName="io.sapl.api.interpreter.Val"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuthorizationSubscription" instanceClassName="io.sapl.api.pdp.AuthorizationSubscription"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FunctionContext" instanceClassName="io.sapl.interpreter.functions.FunctionContext"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuthorizationDecision" instanceClassName="io.sapl.api.pdp.AuthorizationDecision"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Decision" instanceClassName="io.sapl.api.pdp.Decision"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ValMono" instanceTypeName="reactor.core.publisher.Mono&lt;io.sapl.api.interpreter.Val>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PolicyElementList" instanceTypeName="java.util.List&lt;io.sapl.grammar.sapl.PolicyElement>"/>
  <eClassifiers xsi:type="ecore:EClass" name="CombiningAlgorithm" abstract="true">
    <eOperations name="combinePolicies" lowerBound="1" eType="#//CombinedDecisionFlux">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Method which evaluates multiple policies within a policy set against an authorization subscription object, combines the results and creates and returns a corresponding authorization decision object. The method is supposed to be used to determine an authorization decision for the SAPL documents known to the PDP. Imports are obtained from the SAPL document.&#xA;@param policies policies of the set currently matching the ongoing authorization subscription.&#xA;@return a {@link Flux} of {@link io.sapl.api.pdp.AuthorizationDecision} objects containing the combined decision, the combined obligation and advice and a transformed resource if applicable. A new authorization decision object is only pushed if it is different from the previous one."/>
      </eAnnotations>
      <eParameters name="policies" eType="#//PolicyElementList"/>
    </eOperations>
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DenyOverridesCombiningAlgorithm" eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="PermitOverridesCombiningAlgorithm" eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="FirstApplicableCombiningAlgorithm" eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnlyOneApplicableCombiningAlgorithm"
      eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="DenyUnlessPermitCombiningAlgorithm"
      eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="PermitUnlessDenyCombiningAlgorithm"
      eSuperTypes="#//CombiningAlgorithm"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PolicyRetrievalResult" instanceClassName="io.sapl.prp.PolicyRetrievalResult"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DocumentEvaluationResultFlux" instanceTypeName="reactor.core.publisher.Flux&lt;io.sapl.interpreter.DocumentEvaluationResult>"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CombinedDecisionFlux" instanceTypeName="reactor.core.publisher.Flux&lt;io.sapl.interpreter.CombinedDecision>"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DocumentEvaluationResult" instanceClassName="io.sapl.interpreter.DocumentEvaluationResult"
      serializable="false"/>
</ecore:EPackage>
