server:
  port: ${PORT:8091}

vaadin:
  allowed-packages: io.sapl

spring:
  application:
    name: "Attribute API GUI"

io:
  sapl:
    attribute-api-gui:
      admin-username: ${SAPL_GUI_ADMIN_USERNAME:admin}
      admin-password: ${SAPL_GUI_ADMIN_PASSWORD}
      connection:
        base-url: http://localhost:8090
        method: ${METHOD:basic} # none | basic | api
        basic:
          username: ${BASIC_USERNAME:}
          password: ${BASIC_PASSWORD:}
        api:
          key: ${API_KEY:}
