/*
 * SAPL generated by Xtext
 */
package io.sapl.grammar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SAPLUiModule extends AbstractSAPLUiModule {

	public SAPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
