/*
 * Copyright (C) 2017-2025 Dominic Heutelbeck (dominic@heutelbeck.com)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * SAPL generated by Xtext
 */
package io.sapl.grammar.ui.contentassist;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 *
 * This class is effectively unused because the plugin uses an adapter to access
 * {@link SAPLUiContentProposalProvider} instead. It is only required for
 * compilation because it is referenced by autogenerated code in
 * {@link io.sapl.grammar.ui.AbstractSAPLUiModule}. But the relevant method is
 * overridden in {@link io.sapl.grammar.ui.SAPLUiModule}.
 */
public class SAPLProposalProvider extends AbstractSAPLProposalProvider {
}
