//
// Copyright © 2017-2021 Dominic Heutelbeck (dominic@heutelbeck.com)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

:tabsize: 4
:imagesdir: images
= Geo - Location Based Authorization for SAPL
Dominic Heutelbeck
v0.1, 2017-11-17

:toc!:

== General Information
Before the digital age, the place where sensitive information was kept was part of the protective measures to secure it from unwanted access. In today's world of digital information it has become equally important to secure server centers and storage sites from physical access. However, due to the advancements of network technology the person accessing data from these centers could be geographically located anywhere. The only thing he needs is a proper network connection and his credentials to authorize himself.

There are plenty of scenarios in which the current position of the user asking for access plays a vital role. A few ones of those predominantly found in the literature will be presented in the following.

* Medical data of patients are highly sensitive. A clinician shall not be granted access to the medical records of his patients outside of his duty and therefore be allowed to view and edit them only from inside the hospital. 
* A company is working on some innovative ideas and projects that need the highest amount of protection to avoid the risk of being copied by the competition. Therefore it has introduced a _safe room_ that is cut off from the outside world as much as possible. Employees working on the innovative projects can only access related data when they are inside this room.
* Military documents that are classified on a certain confidentiality level must only be accessed from within the military base. Therefore the access is only granted if the user is inside.

To put an authorization control in this form into practice, the concept of *location based access* (LBA) was created. As SAPL is an attribute-based access control (ABAC) with his architectural patterns based on http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html[XACML] it seems intuitively to introduce geographical functions and attributes into policies and thereby allow LBA. This is exactly what the SAPL-Geo module establishes. 

== User guidelines
=== Geometries
==== Supported types
As SAPL is loosely based on the patterns and structure of http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html[XACML] it is the obvious choice to make use of the http://www.opengeospatial.org/standards/geoxacml[GeoXACML standard] for implementing a LBA approach. GeoXACML is a geo-specific extension of the XACML standard that has its main strength in  declaring and enforcing access rights for geospatial data (e.g. in geographic information system, etc.) in a flexible way. This is clearly not the exact purpose of the SAPL-Geo extension, however, as the two domains are quite similar all of these functions and operations become useful in the environment of LBA as well.

In accordance with this standard the following geometries are available in SAPL-Geo. Additionally, one or more of these geometries can be grouped together in a common `GeometryCollection` object.

.Geometries provided in SAPL-Geo according to the http://portal.opengeospatial.org/files/?artifact_id=42734[GeoXACML specification]
[options="header",cols="1,3"]
|======================
|Geometry | Explanation
|Point | A Point is a 0-dimensional geometric object and represents a single location in
coordinate space. A Point has an x-coordinate value, a y-coordinate value. 
|LineString | A LineString is a Curve with linear interpolation between Points. Each
consecutive pair of Points defines a Line segment.
|Polygon | A Polygon is a planar Surface defined by 1 exterior boundary and 0 or more
interior boundaries. Each interior boundary defines a hole in the Polygon. 
|MultiPoint | A MultiPoint is a 0-dimensional GeometryCollection. The elements of a
MultiPoint are restricted to Points.
|MultiLineString | A MultiLineString is a MultiCurve whose elements are LineStrings. 
|MultiPolygon | A MultiPolygon is a MultiSurface whose elements are Polygons.
|======================

==== Supported data formats
In general there are multiple standards to exchange and store geometric objects. SAPL-Geo makes vastly use of GeoJSON, as the general syntax and object mapping in SAPL already support the JSON-format. However, as external systems frequently work with other standards as well, the following most common ones are supported.

GeoJSON:: http://geojson.org/[The GeoJSON-Standard] is based on https://tools.ietf.org/html/rfc7946[RFC 7946] and aligns itself exactly with the requirements that are imposed by GeoXACML. Please note that for reasons of simplicity the `Feature` and `FeatureCollection` parts are not supported in SAPL-Geo.

IMPORTANT: GeoJSON is the only format that is accepted right inside of policies and variables. The other supported formats can be used only within the AttributeFinder or Java source code.

----
{
   "pointOne":{ 
	"type": "Point",
	"coordinates":
			[10.0, 15.0]
	}
}
----

Well-known Text (WKT):: Well-known Text (WKT) was originally defined by the http://www.opengeospatial.org/ogc[Open Geospatial Consortium (OGC)] and is described in detail in the http://docs.opengeospatial.org/is/12-063r5/12-063r5.html[ISO 19162:2015 specification]. It provides an easy and readable way of representing geometric objects and spatial features. 

----
POINT (10 15)
----

Keyhole Markup Language (KML):: The Keyhole Markup Language (KML) is a XML-based standard by the http://www.opengeospatial.org/ogc[OGC] and is described in the http://portal.opengeospatial.org/files/?artifact_id=23689[best practices]. It mainly became famous for the use in Google Earth and associated software and uses WGS84 as the only CRS. Geometries from KML files can be loaded into policies via the AttributeFinder either from the filesystem or a HTTP-address (see <<sec:kml, KML Import>>).



=== Coordinate Reference Systems
SAPL-Geo supports the projection of coordinates into different coordinate reference systems (CRS). Depending on how the geospatial data is extracted from third party systems, this might be required to facilitate comparisons and to simplify the use of the provided geospatial functions. The CRS are loaded from the https://www.epsg-registry.org/[EPSG Geodetic Parameter Dataset] and identified by their respective codes (e.g. _EPSG:4326_ for the WGS84-CRS). 

Two different parameters are required retrieve a mathematical transformation for a projection:

Source CRS:: The Source CRS is the system that decoded the coordinates of the external data. 

Destination CRS:: The Destination CRS is the system into which the coordinates will be projected. 

Usually you would first have to define a projection via the `getProjection`-function and thereafter convert your data with the `project`-function. Detailed information about the syntax can be found in the <<sec:function_reference, Function reference>>.


=== Embedding the module
To use the SAPL-Geo FunctionLibrary a new instance of `GeoFunctionLibrary` has to be loaded into the `FunctionContext`. The `GeoPolicyInformationPoint` is included into the `AttributeContext` analogously as the following code shows.

[source,java]
----
FUNCTION_CTX.loadLibrary(new GeoFunctionLibrary()); <1>
ATTRIBUTE_CTX.loadPolicyInformationPoint(new GeoPolicyInformationPoint()); <2>
----

<1> Loads a new instance of `GeoFunctionLibrary` into the `FunctionContext`.
<2> Loads the `GeoPolicyInformationPoint` into the `AttributeContext`.

If the Policy Decision Point (PDP) is configured via a `pdp.json` one would just have to add `io.sapl.pip.geo` to the AttributeFinders and `geo` to the libraries.
     
That way all geographical functions are registered to the SAPL interpreter and can be accessed within policies via the keyword `geo`. For an exhaustive list of all provided functions and their syntax please refer to the <<sec:function_reference, Function Reference>> or <<sec:attribute_reference, Attribute Reference>> respectively. The following sample demonstrates the use of the library within a policy description:


.Sample policy using a geographical function
----
val userPos := subject.username.<sapl.geo.tracker>.position; <1>
val hospital := subject.institution.<sapl.geo.gis>.geofences.hospital; <2>

policy "SAPL-Geo Sample"
permit resource =~ "^https://medical.org/api/patients.*"
where
  subject.username.<user.profile>.group == "doctor";
  geo.within(userPos, hospital); <3>
----

<1> Loads the current geographical position of the user from an external tracking software that is connected to the policy engine via the `GeoPolicyInformationPoint`.
<2> Loads a polygon object describing the geographical area of the hospital from an external geographic information system (GIS) that is connected to the policy engine via the `GeoPolicyInformationPoint`.
<3> Uses the function `within` from the `GeoFunctionLibrary` to check, whether the user position is currently inside the hospital or not. 

TIP: All possible fields that are returned from the `GeoPolicyInformationPoint` are listed in the <<sec:geopipresponse, Response object>>.


[[sec:attribute_reference]]
== Attribute reference
To make the best use from location based authorization it is usually required to connect external systems to the policy engine to retrieve certain data (such as the user location, geofences from an external library, etc.). These systems could comprise tracking system, mobile device management systems (MDM) or even geographic information systems (GIS). Unfortunately there does not yet exist one standardized interface or protocol to retrieve data from different sources, which is why the `GeoPolicyInformationPoint` is build in a modular way. Each module makes use of a standard data exchange formats wherever possible and on top provides an individual configuration for the specific system to connect to. There are already a few connection adapters predefined but it is, of course, left open to the developer to write an own adapter to integrate a particular system. Additionally, a common standardized format is defined for the responses which is described in <<sec:geopipresponse, Response object>>.

=== PostGIS
http://postgis.net/[PostGIS] is a geo-spatial extension to https://www.postgresql.org[PostgreSQL] object-relational databases. It has become very popular especially within open source applications and is widely used for storing and querying geo-spatial data. Therefore multiple servers, applications and tools use PostGIS as their database backend. SAPL-Geo is therefore able to connect to such a database as well, retrieve geometries of interest and make them accessible directly from within policies. 

A PostGIS database can be connected via the AttributeFinder `io.sapl.pip.geo.postgis` while the configuration has to be in the following format.

[[postgisconfig]]
.Structure of the configuration for the PostGIS Policy Information Point
[source,java]
----
public class PostGISConfig {
    private String serverAddress; <1>
    private String port; <2>
    private String db; <3>
    private String table; <4>
    private String username; <5>
    private String password; <6>
    private String pkColName; <7>
    private String idColName; <8>
    private String geometryColName; <9>
    private int from; <10>
    private int until; <11>
    private int projectionSRID; <12>
    private boolean flipCoordinates; <13>
    private boolean ssl; <14>
    private String urlParams; <15>
}
----

<1> Address (URL) of the PostGIS database.
<2> Port of the PostGIS database.
<3> Name of the database to be imported.
<4> Name of the table to be imported.
<5> Username to access the database.
<6> Password to access the database.
<7> Name of the column that holds the primary key of the data.
<8> Name of the column that holds the descriptive name of the data. This name will later be used to identify the geofences in the polices.
<9> Name of the column that holds the geometries.
<10> Numeric start primary key, from which the geometries shall be imported.
<11> Numeric end primary key, until which the geometries shall be imported. If none is provided, all geometries beginning from *10* are imported.
<12> The SRID into which the coordinates will be projected during the import. If no projection is required the field can just be left empty or assigned a `0` instead.
<13> Boolean to decide, whether the coordinates shall be flipped before being imported into the policy. The rationale here is, that GIS-databases usually store `X` and `Y` values, whereas SAPL-Geo works with Latitude and Longitude values (see http://postgis.net/2013/08/18/tip_lon_lat/[this arcticle] for further information).
<14> Establishes a SSL-connection to the database if set to `true`. Please note that server certificate (respectively the CA of the servers certificate) must be trusted in a TrustStore. Further options can be set in the custom `urlParams` field.
<15> Further arguments that can be specified freely and will be passed when establishing the connection to the database. Multiple parameters must be delimited using the `&`-sign.


[[sec:kml]]
=== KML Import
KML-files can be imported into SAPL policies via the PIP `sapl.pip.geo.kml`, whereby the configuration only exists of the filename (that must exist in a predefined directory) or the HTTP/HTTPS-address. All `<Placemark>` attributes will be imported and made accessible via their `<Name>` tags.

IMPORTANT: A bug is currently present in the GeoTools KML import dependency. If a `<LookAt>` tag exists within a `<Placemark>` tag in the KML-file, only the very first geometry within the `<MultiGeometry>` will be imported.

=== Traccar
https://www.traccar.org[Traccar] is a fleet managing and tracking software. Multiple devices can log their GPS systems onto the server. Furthermore, the frontend also allows for an easy creation and configuration of geofences. The PIP `sapl.pip.geo.traccar` connects to the Traccar server via a RESTful service and therefore requires the following configuration:

[[traccarconfig]]
.Structure of the configuration for the Traccar Policy Information Point
[source,java]
----
public class TraccarConfig {
    private String url; <1>
    private String deviceID; <2>
    private String credentials; <3>
    private String username; <4>
    private String password; <5>
    private int posValidityTimespan; <6>
}
----

<1> Address (URL) of the Traccar server.
<2> ID of the device from which the information shall be retrieved.
<3> Base64-encoded string of username and password to access the Traccar server (can be replaced by giving *4* and *5* alternatively).
<4> Username to access the Traccar server.
<5> Password to access the Traccar server.
<6> Timeframe in minutes, during which the last position update must have taken place to be considered as a current position.


[[sec:geopipresponse]]
=== Response object

To facilitate and standardize the use of the the `GeoPolicyInformationPoint` within SAPL policies, all the individual modules respond to requests in a common way. Hence, a general skeleton in form of a `GeoPIPResponse` is being created, which holds all the relevant information. It is basically divided into two parts, whereby the first one (<1> until <6>) holds information about the user's position and the other one (<6>) stores geometries/geofences. If a certain value cannot be retrieved from the source system, the respective value in the response equals the standard value for the datatype or is empty instead.

[[geopipresponse]]
.Structure of the response class for the GeoPolicyInformationPoint
[source,java]
----
public class GeoPIPResponse {
    private final String identifier; <1>
    private final JsonNode position; <2>
    private final double altitude; <3>
    private final String lastUpdate; <4>
    private final double accuracy; <5>
    private final double trust; <6>
    private final ObjectNode geofences; <7>
}
----

<1> A general identifier. Depending on the specific request it could e.g. represent a device-ID that has been tracked or the common name of a collection of geofences.
<2> The user's position as a GeoJSON point object. Can be utilized for immediate further use in all functions of the GeoFunctionLibrary.
<3> The altitude relating to the user's position.
<4> Time and date of the last position update of the user. Formatted in the ISO 8601 standard for further use in the respective time and date function libraries.
<5> Estimated position error of the user's position in [m]. It is usually calculated by the respective tracking or positioning systems.
<6> Trust value of the users position. The value on a scale between 0 (not trusted) and 1 (fully trustworthy) represents e.g. how easily the position could be spoofed (obviously depending on the used tracking system).
<7> Collection of geofences in which each one can be addressed by its name (see sample below).

.Sample JSON-Response from the GeoPolicyInformationPoint
----
{  
   "identifier":"DeviceID",
   "position":{  
      "type":"Point",
      "coordinates":[50.1, 4.5]
   },
   "altitude":100.0,
   "geofences":{  
      "Mainz":{  
         "type":"Polygon",
         "coordinates":[  
            [  
               [50.0329, 8.2297],
               [49.9998, 8.1802],
               [49.9406, 8.2352],
               [49.9459, 8.3323],
               [49.9837, 8.3821],
               [50.0329, 8.3721],
               [50.0329, 8.2297]
            ]
         ]
      }
   },
   "lastUpdate":"2017-10-01T10:10:00.000+0000",
   "accuracy":10.1,
   "trust":1.0
}
----


[[sec:function_reference]]
== Function reference

=== Index
* <<sec:topo, Topological Functions>>
** `<<equals, equals(Geometry geometry1, Geometry geometry2)>>`
** `<<disjoint, disjoint(Geometry geometry1, Geometry geometry2)>>`
** `<<touches, touches(Geometry geometry1, Geometry geometry2)>>`
** `<<crosses, crosses(Geometry geometry1, Geometry geometry2)>>`
** `<<within, within(Geometry geometry1, Geometry geometry2)>>`
** `<<contains, contains(Geometry geometry1, Geometry geometry2)>>`
** `<<overlaps, overlaps(Geometry geometry1, Geometry geometry2)>>`
** `<<intersects, intersects(Geometry geometry1, Geometry geometry2)>>`
* <<sec:constr, Constructive Geometric Functions>>
** `<<buffer, buffer(Geometry geometry, double bufferwidth)>>`
** `<<boundary, boundary(Geometry geometry)>>`
** `<<convexhull, convexHull(Geometry geometry)>>`
** `<<centroid, centroid(Geometry geometry)>>`
** `<<difference, difference(Geometry geometry1, Geometry geometry2)>>`
** `<<symdifference, symdifference(Geometry geometry1, Geometry geometry2)>>`
** `<<intersection, intersection(Geometry geometry1, Geometry geometry2)>>`
** `<<union, union(Geometry geometry1, Geometry geometry2)>>`
* <<sec:scalar, Scalar Geometric Functions>>
** `<<area, area(Geometry geometry)>>`
** `<<distance, distance(Geometry geometry1, Geometry geometry2)>>`
** `<<geodistance, geoDistance(Geometry geometry1, Geometry geometry2)>>`
** `<<iswithindistance, isWithinDistance(Geometry geometry1, Geometry geometry2, double distance)>>`
** `<<iswithingeodistance, isWithinGeoDistance(Geometry geometry1, Geometry geometry2, double distance)>>`
** `<<length, length(Geometry geometry)>>`
* <<sec:special, Functions to check special characteristics>>
** `<<issimple, isSimple(Geometry geometry)>>`
** `<<isclosed, isClosed(Geometry geometry)>>`
** `<<isvalid, isValid(Geometry geometry)>>`
** `<<getproj, getProjection(String srcSystem, String destSystem)>>`
** `<<project, project(Geometry geometry, Projection projection)>>`
* <<sec:geocoll, Functions for GeometryCollections>>
** `<<restogeombag, resToGeometryBag(Object geometry,...)>>`
** `<<oneandonly, oneAndOnly(GeometryCollection geoCollection)>>`
** `<<bagsize, bagSize(GeometryCollection geoCollection)>>`
** `<<geometryisin, geometryIsIn(Geometry geometry, GeometryCollection geoCollection)>>`
** `<<geometrybag, geometryBag(Geometry geometry,...)>>`
** `<<atleastonememberof, atLeastOneMemberOf(GeometryCollection geoCollection1, GeometryCollection geoCollection2)>>`
** `<<subset, subset(GeometryCollection geoCollection1, GeometryCollection geoCollection2)>>`
* <<sec:conv, Conversion Functions>>
** `<<tometer, toMeter(double value, String unit)>>`
** `<<tosquaremeter, toSquareMeter(double value, String unit)>>`
* <<sec:proj, Projection Functions>>
** `<<getProjection, getProjection(String fromCrs, String toCrs)>>`
** `<<project, project(Geometry geom, Projection mathTransform)>>`

[[sec:topo]]
=== Topological Functions

***************
[[equals]]
`*equals(Geometry geometry1, Geometry geometry2)*`

---

Tests if two geometries are exactly (!) equal.

Parameter::
`geometry1`, `geometry2` - the geometries to test, can also be from type `GeometryCollection`
	
Returns::
`true` if the geometries are equal, i.e. contain exactly the same points
***************

***************
[[disjoint]]
`*disjoint(Geometry geometry1, Geometry geometry2)*`

---

Tests if two geometries are disjoint from each other (not intersecting each other). It is the inverse of the `<<intersects, intersects()>>` function.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if the geometries have absolutely no point in common
***************

***************
[[touches]]
`*touches(Geometry geometry1, Geometry geometry1)*`

---

Tests if two geometries are touching each other.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if the geometries have no interior points in common, but at least one boundary point 	
***************

***************
[[crosses]]
`*crosses(Geometry geometry1, Geometry geometry1)*`

---

Tests if two geometries are crossing each other.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if the geometries have a common intersecting area which area is less than that of both geometries and neither geometry is contained in the other
***************

***************
[[within]]
`*within(Geometry geometry1, Geometry geometry1)*`

---

Tests if the `geometry1` is fully included in `geometry2`. It is the converse of the `<<contains, contains()>>` function.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if every point of `geometry1` is also in `geometry2`
***************

***************
[[contains]]
`*contains(Geometry geometry1, Geometry geometry1)*`

---

Tests if the `geometry1` fully contains `geometry2`. It is the converse of the `<<within, within()>>` function.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if every point of `geometry2` lies within (the closure of) `geometry1`
***************

***************
[[overlaps]]
`*overlaps(Geometry geometry1, Geometry geometry1)*`

---

Tests if two geometries are overlapping.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if the geometries share some but not all points and this intersection is of the same dimension as the geometries
***************

***************
[[intersects]]
`*intersects(Geometry geometry1, Geometry geometry1)*`

---

Tests if two geometries have at least one common intersection point. It is the inverse of the `<<disjoint, disjoint()>>` function.

Parameter::
`geometry1`, `geometry2` - the geometries to test
	
Returns::
`true` if two geometries have at least one common intersection point
***************

[[sec:constr]]
=== Constructive Geometric Functions

***************
[[buffer]]
`*buffer(Geometry geometry, double bufferwidth)*`

---

Computes a buffer area of `bufferwidth` around `geometry`.

Parameter::
`geometry` - the geometries to add the buffer to
install 
+
`bufferwidth` - the width of the buffer in units specified by the map projection of the coordinates
	
Returns::
a new `Geometry`-object that contains all points within a distance of `bufferwidth` of `geometry`
***************

***************
[[boundary]]
`*boundary(Geometry geometry)*`

---

Computes the boundary of`geometry`.

Parameter::
`geometry` - the geometries to return the boundary from
	
Returns::
a new `Geometry`-object resembling the boundary of `geometry`
***************

***************
[[convexhull]]
`*convexHull(Geometry geometry)*`

---

Computes the convex hull (smallest convex polygon, that contains all points of the geometry) of `geometry`.

Parameter::
`geometry` - the geometries to retrieve the convex hull from
	
Returns::
a new `Geometry`-object resembling the convex hull of `geometry`
***************

***************
[[centroid]]
`*centroid(Geometry geometry)*`

---

Computes a point that is the geometric center of gravity of `geometry`.

Parameter::
`geometry` - the geometries to retrieve the centroid from
	
Returns::
a new `Geometry`-object resembling the centroid of `geometry`
***************

***************
[[difference]]
`*difference(Geometry geometry1, Geometry geometry2)*`

---

Computes the closure of the set difference between two geometries. 

Parameter::
`geometry1`, `geometry2` - the geometries to retrieve the difference from
	
Returns::
a new `Geometry`-object containing all points which lie in `geometry1` but not in `geometry2`
***************

***************
[[symdifference]]
`*symDifference(Geometry geometry1, Geometry geometry2)*`

---

Computes the closure of the symmetric difference between two geometries.

Parameter::
`geometry1`, `geometry2` - the geometries to retrieve the symmetric difference from
	
Returns::
a new `Geometry`-object containing all points which lie in either `geometry1` or in `geometry2` but not in both of them
***************

***************
[[intersection]]
`*intersection(Geometry geometry1, Geometry geometry2)*`

---

Computes the the point set intersection of the geometries.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the intersection from, can also be of type `GeometryCollection`
	
Returns::
a new `Geometry`-object containing the common points of both geometries
***************

***************
[[union]]
`*union(Geometry geometry1, Geometry geometry2)*`

---

Computes the union of two geometries.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the union from, can also be of type `GeometryCollection`
	
Returns::
a new `Geometry`-object containing the union of both geometries
***************

[[sec:scalar]]
=== Scalar Geometric Functions

***************
[[area]]
`*area(Geometry geometry)*`

---

Computes the area of the geometry.

Parameter::
`geometry` - the geometry to calculate the area of

Returns::
the area of `geometry`. The returned value is in the units (squared) specified by the map projection of the coordinates
***************

***************
[[distance]]
`*distance(Geometry geometry1, Geometry geometry2)*`

---

Calculates the (shortest) geometric (planar) distance between two geometries.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the distance of

Returns::
the distance of  the geometries. The returned value is in the unit specified by the map projection of the coordinates
***************


***************
[[geodistance]]
`*geoDistance(Geometry geometry1, Geometry geometry2)*`

---

Calculates the (shortest) geodetic distance of two geometries in [m] based on the WGS84 ellipsoid.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the distance of, their coordinates must be in the WGS84-CRS

Returns::
the geodetic distance of the geometries in [m]
***************

***************
[[iswithindistance]]
`*isWithinDistance(Geometry geometry1, Geometry geometry2, double distance)*`

---

Tests if two geometries are within the given geometric (planar) distance of each other.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the distance of
+
`distance` - the distance to test in the unit specified by the map projection of the coordinates

Returns::
`true` if the two geometries are within `distance`
***************

***************
[[iswithingeodistance]]
`*isWithinGeoDistance(Geometry geometry1, Geometry geometry2, double distance)*`

---

Tests if two geometries are within the given geodetic distance of each other based on the WGS84-ellipsoid.

Parameter::
`geometry1`, `geometry2` - the geometries to calculate the distance of, their coordinates must be in the WGS8-CRS
+
`distance` - the distance to test in [m]

Returns::
`true` if the two geometries are within geodetic `distance`
***************

***************
[[length]]
`*length(Geometry geometry)*`

---

Computes the length of the geometry (perimeter in case of areal geometries). 

Parameter::
`geometry` - the geometry to calculate the length of

Returns::
the length of `geometry`. The returned value is in the unit specified by the map projection of the coordinates.
***************

[[sec:special]]
=== Functions to check special characteristics

***************
[[issimple]]
`*isSimple(Geometry geometry)*`

---

Checks if the geometry has no anomalous geometric points (e.g. self interesection, self tangency,...).

Parameter::
`geometry` - the geometry to test

Returns::
`true` if the geometry has no anomalous geometric points
***************

***************
[[isclosed]]
`*isClosed(Geometry geometry)*`

---

Checks if the geometry is either empty or from type (Multi)Point or a closed (Multi)LineString.

Parameter::
`geometry` - the geometry to test

Returns::
`true` if the geometry is closed as described above
***************

***************
[[isvalid]]
`*isValid(Geometry geometry)*`

---

Checks if the geometry is topologically valid according to OGC specifications

Parameter::
`geometry` - the geometry to test

Returns::
`true` if the geometry is valid as described above
***************
***************
[[getproj]]
`*getProj(String srcSystem, String destSystem)*`

---

Calculates a math transformation to project from the source CRS into the destination CRS. 

Parameter::
`srcSystem` - EPSG code of the source CRS
`destSystem` - EPSG code of the destination CRS

Returns::
a definition of a math transformation in WKT-format
***************
***************
[[project]]
`*project(Geometry geometry, Projection projection)*`

---

Projects the given geometry according to the projection

Parameter::
`geometry` - the geometry to project
`projection` - WKT-coded math transformation for the projection

Returns::
the projected geometry
***************

[[sec:geocoll]]
=== Functions for GeometryCollections

***************
[[restogeombag]]
`*resToGeometryBag(Object geometry,...)*`

---

Puts any number of JsonObjects that contain geometries into one GeometryCollection. Can be used e.g. to store all objects returned by `GeoPIPResponse.geofences` in one GeometryCollection

Parameter::
`geometry` - JsonObject containing geometries

Returns::
a GeometryCollection containing all geometries that were given as input parameter 
***************

***************
[[oneandonly]]
`*oneAndOnly(GeometryCollection geoCollection)*`

---

Returns the only element of `geoCollection`.

Parameter::
`geoCollection` - the GeometryCollection to use

Returns::
the only element of `geoCollection` if `geoCollection` contains only one element. In all other cases an error will be thrown resulting in the SAPL-decision being INTERDETERMINATE. 
***************

***************
[[bagsize]]
`*bagSize(GeometryCollection geoCollection)*`

---

Determines the number of elements in `geoCollection`.

Parameter::
`geoCollection` - the GeometryCollection to use

Returns::
the number of elements in `geoCollection` as `double`
***************

***************
[[geometryisin]]
`*geometryIsIn(Geometry geometry, GeometryCollection geoCollection)*`

---

Tests if `geometry` is in `geoCollection`.

Parameter::
`geometry` - the geometry to check
+
`geoCollection` - the GeometryCollection to use

Returns::
`true` if `geometry` is in `geoCollection`
***************

***************
[[geometrybag]]
`*geometryBag(Geometry geometry,...)*`

---

Puts any number of geometries into a `GeometryCollection`.

Parameter::
`geometry` - the geometries to put into a collection

Returns::
a `GeometryCollection` containing all input `geometry` 
***************

***************
[[atleastonememberof]]
`*atLeastOneMemberOf(GeometryCollection geoCollection1, GeometryCollection geoCollection2)*`

---

Checks if at least one member of `geoCollection1` is in `geoCollection2`.

Parameter::
`geoCollection1`, `geoCollection2` - the geometry collections to check

Returns::
`true` if at least one member of `geoCollection1` is in `geoCollection2`
***************

***************
[[subset]]
`*subset(GeometryCollection geoCollection1, GeometryCollection geoCollection2)*`

---

Checks if `geoCollection1` is a subset of `geoCollection2`.

Parameter::
`geoCollection1`, `geoCollection2` - the geometry collections to check

Returns::
`true` if all members of `geoCollection1` are in `geoCollection2`
***************

[[sec:conv]]
=== Conversion Functions

***************
[[tometer]]
`*toMeter(double value, String unit)*`

---

Converts the given `value` from [`unit`] to [m].

Parameter::
`value` - the value to convert
+
`unit` - the unit of the value (according to the notation of javax.measures.unit) 

Returns::
the converted as value as `double`
***************


***************
[[tosquaremeter]]
`*toSquareMeter(double value, String unit)*`

---

Converts the given `value` from [`unit`] to [m^2].

Parameter::
`value` - the value to convert
+
`unit` - the unit of the value (according to the notation of javax.measures.unit) 

Returns::
the converted as value as `double`
***************

[[sec:proj]]
=== Projection Functions

***************
[[getProjection]]
`*getProjection(String fromCrs, String toCrs)*`

---

Calculates a mathematical transformation to convert from `fromCrs` to `toCrs`.

Parameter::
`fromCrs` - the EPSG-Code of the coordinate reference system to be converted from
+
`toCrs` - the EPSG-Code of the coordinate reference system to be converted from

Returns::
a mathematical conversion decoded in the WKT format to be further used in the `project`-function
***************

***************
[[project]]
`*project(Geometry geom, Projection mathTransform)*`

---

Projects `geom` according to the given `mathTransform`

Parameter::
`geom` - the geometry to project
+
`mathTransform` - the mathematical conversion (can be retrieved via the `getProjection`-function

Returns::
the projected geometry
***************

