server:
  port: ${PORT:8080}
  servlet:
    session:
      persistent: false
      cookie:
        same-site: none
        secure: true

vaadin:
  allowed-packages: io.sapl

sapl:
  embed:
    cors:
      allowed-origins:
        - http://localhost:9000

logging:
  level:
    org.atmosphere: error
    org.springframework.boot.devtools.restart.ChangeableUrls: warn
    io.sapl.lsp.core.ConfigurationManager: warn
    io.sapl.lsp.core.document.DocumentManager: warn
    io.sapl.lsp.server.SAPLLanguageServer: warn
    io.sapl.pdp.configuration.PdpVoterSource: error
    org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer: error
    io.sapl.vaadin: info
    io.sapl.vaadin.lsp.LspWebSocketEndpoint: off
    io.sapl.playground.ui: info
