/*
 * generated by Xtext 2.13.0
 */
package io.sapl.grammar


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SAPLRuntimeModule extends io.sapl.grammar.AbstractSAPLRuntimeModule {
}
