name: "🐞 Bug Report"
description: "Report a bug in this project."
labels: ["bug"]

body:

  - type: markdown
    attributes:
      value: |
        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our Code of Conduct and Contributing Guidelines at this repository.

        **SECURITY RELATED?** Please view our [security policy](https://github.com/heutelbeck/sapl-policy-engine/blob/master/SECURITY.md).

  - type: textarea
    id: bug-report
    attributes:
      label: "What went wrong?"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: "How to reproduce?"
      description: "Provide reproducer, code examples, or description for a minimal scenario to replicate the bug."
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: "What did you expect?"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Your environment"

  - type: input
    id: sapl-version
    attributes:
      label: "Which SAPL version is used?"
      description: "e.g. 2.0.1 / 3.0.0-SNAPSHOT ({DATE}) ..."
    validations:
      required: false

  - type: input
    id: java-version
    attributes:
      label: "Which Java version is used?"
      description: "e.g. OpenJDK 11.0.8 / Oracle JDK 1.8.0_261 ..."
    validations:
      required: false
      
  - type: input
    id: operating-system
    attributes:
      label: "Which OS is running?"
      description: "e.g. Ubuntu 5.4.0-26-generic x86_64 / Windows 1904 ..."
    validations:
      required: false

