name: "🔧 Enhancement Request"
description: "Request an enhancement for this project."
labels: ["enhancement"]

body:

  - type: markdown
    attributes:
      value: |
        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our Code of Conduct and Contributing Guidelines at this repository.

  - type: textarea
    attributes:
      label: "Is your enhancement request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false