io.sapl:
  server-lt:
    allowNoAuth: False
    allowBasicAuth: False
    allowApiKeyAuth: False
    allowOauth2Auth: False
  pdp.embedded:
    config-path: /pdp/data
    policies-path: /pdp/data
spring:
  config.location: file:/pdp/data
loader.path: /pdp/data/lib
logging.level:
  "[org.springframework]": INFO
  "[io.sapl]": INFO
  