/*
 * SAPL generated by Xtext 2.20.0
 */
package io.sapl.grammar.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SAPLWebModule extends AbstractSAPLWebModule {
}
