/*
 * generated by Xtext 2.13.0
 */
package io.sapl.grammar.ide

import com.google.inject.Guice
import io.sapl.grammar.SAPLRuntimeModule
import io.sapl.grammar.SAPLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SAPLIdeSetup extends SAPLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SAPLRuntimeModule, new SAPLIdeModule))
	}
	
}
