/*
 * Copyright (C) 2017-2024 Dominic Heutelbeck (dominic@heutelbeck.com)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar.validation;

import java.time.format.DateTimeParseException;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

import org.eclipse.xtext.validation.Check;

import io.sapl.test.grammar.sapltest.Duration;
import io.sapl.test.grammar.sapltest.Multiple;
import io.sapl.test.grammar.sapltest.StringMatchesRegex;
import io.sapl.test.grammar.sapltest.StringWithLength;
import io.sapl.test.grammar.sapltest.TestCase;
import io.sapl.test.grammar.sapltest.VirtualTime;

/**
 * This class contains custom validation rules.
 * <p>
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SAPLTestValidator extends AbstractSAPLTestValidator {
    protected static final String MSG_INVALID_JAVA_DURATION = "Duration is not a valid Java Duration";

    protected static final String MSG_INVALID_MULTIPLE_AMOUNT                  = "Amount needs to be a natural number larger than 1";
    protected static final String MSG_TESTCASE_WITH_MORE_THAN_ONE_VIRTUAL_TIME = "TestCase contains more than one virtual-time declaration";
    protected static final String MSG_STRING_MATCHES_REGEX_WITH_INVALID_REGEX  = "The given regex has an invalid format";
    protected static final String MSG_INVALID_STRING_WITH_LENGTH               = "String length needs to be an natural number larger than 0";

    /**
     * Duration string needs to represent a valid Java Duration
     *
     * @param duration a Duration string
     */
    @Check
    public void durationNeedsToBeAValidJavaDuration(final Duration duration) {
        try {
            java.time.Duration.parse(duration.getDuration());
        } catch (DateTimeParseException e) {
            error(MSG_INVALID_JAVA_DURATION, duration, null);
        }
    }

    /**
     * Multiple amount needs to be a natural number larger than 1
     *
     * @param multiple a Multiple instance
     */
    @Check
    public void multipleAmountNeedsToBeNaturalNumberLargerThanOne(final Multiple multiple) {
        var isValid = true;
        try {
            if (multiple.getAmount().intValueExact() < 2) {
                isValid = false;
            }
        } catch (ArithmeticException exception) {
            isValid = false;
        }
        if (!isValid) {
            error(MSG_INVALID_MULTIPLE_AMOUNT, multiple, null);
        }
    }

    /**
     * TestCase may contain virtual-time only once
     *
     * @param testCase a TestCase instance
     */
    @Check
    public void testCaseMayContainVirtualTimeOnlyOnce(final TestCase testCase) {
        if (testCase.getGivenSteps().stream().filter(VirtualTime.class::isInstance).count() > 1) {
            error(MSG_TESTCASE_WITH_MORE_THAN_ONE_VIRTUAL_TIME, testCase, null);
        }
    }

    /**
     * StringMatchesRegex may contain only a valid Regex
     *
     * @param stringMatchesRegex a StringMatchesRegex instance
     */
    @Check
    public void stringMatchesRegexMustContainValidRegex(final StringMatchesRegex stringMatchesRegex) {
        try {
            Pattern.compile(stringMatchesRegex.getRegex());
        } catch (PatternSyntaxException e) {
            error(MSG_STRING_MATCHES_REGEX_WITH_INVALID_REGEX, stringMatchesRegex, null);
        }
    }

    /**
     * StringWithLength length needs to be a natural number larger than 0
     *
     * @param stringWithLength a StringWithLength instance
     */
    @Check
    public void stringWithLengthNeedsToBeNaturalNumberLargerThanZero(final StringWithLength stringWithLength) {
        var isValid = true;
        try {
            if (stringWithLength.getLength().intValueExact() < 1) {
                isValid = false;
            }
        } catch (ArithmeticException exception) {
            isValid = false;
        }
        if (!isValid) {
            error(MSG_INVALID_STRING_WITH_LENGTH, stringWithLength, null);
        }
    }

}
