/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SAPLTestValidator extends AbstractSAPLTestValidator { }
