/*
 * Copyright (C) 2017-2025 Dominic Heutelbeck (dominic@heutelbeck.com)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * SAPL generated by Xtext
 */
package io.sapl.grammar.ui;

import com.google.inject.Binder;
import io.sapl.grammar.ide.contentassist.ContentAssistConfigurationSource;
import io.sapl.grammar.ide.contentassist.DefaultContentAssistConfiguration;
import io.sapl.grammar.ui.contentassist.SAPLUiContentProposalProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ui.editor.contentassist.IContentProposalProvider;
import org.eclipse.xtext.ui.editor.contentassist.UiToIdeContentProposalProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SAPLUiModule extends AbstractSAPLUiModule {

    public SAPLUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public void configure(Binder binder) {
        super.configure(binder);
        binder.bind(ContentAssistConfigurationSource.class)
                .toInstance(DefaultContentAssistConfiguration.Factory.create());
    }

    @Override
    public Class<? extends IContentProposalProvider> bindIContentProposalProvider() {
        return UiToIdeContentProposalProvider.class;
    }

    public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
        return SAPLUiContentProposalProvider.class;
    }

}
