/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar;


import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SAPLTestStandaloneSetup extends SAPLTestStandaloneSetupGenerated {

	public static Injector doSetupAndGetInjector() {
		return new SAPLTestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
