/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SAPLTestRuntimeModule extends AbstractSAPLTestRuntimeModule {
}
