/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SAPLTestStandaloneSetup extends SAPLTestStandaloneSetupGenerated {

	public static void doSetup() {
		new SAPLTestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
