#
# Copyright (C) 2017-2023 Dominic Heutelbeck (dominic@heutelbeck.com)
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    admin-username: demo
    encoded-admin-password: "{bcrypt}$2y$12$1yBhnA.SfCzTfNrChI/HNuoqz3k/RCG9iXCbQMRje96hnx1DsfPeq"
# H2
spring:
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:file:~/sapl/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: false
# SSL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty
logging.level:
  "[io.sapl]": TRACE
  "[io.sapl.server.ce]": INFO
 