#
# Copyright (C) 2017-2023 Dominic Heutelbeck (dominic@heutelbeck.com)
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# The configuration is loaded from a config tree mounted as a volume under the given path
# The config tree should contain all parameters commented out below:
# If SSL should be added it can be added there as well following normal Spring conventions
spring:
  config.import: configtree:/etc/config/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/sapl
#    username: root
#    password: testdb
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB53Dialect
#io.sapl:
#  server:
#    admin-username: user
#    # Security (BCrypt encoded client-secret (raw secret: Fa4zvYQdiwHZVXh))
#    encoded-admin-password: "{bcrypt}$2a$10$PhobF71xYb0MK8KubWLB7e0Dpl2AfMiEUi9dkKTbFR4kkWABrbiyO"
    