/*
 * SAPLTest generated by Xtext
 */
package io.sapl.test.grammar.web;

/**
 * Use this class to register additional components to be used within the web
 * application.
 */
public class SAPLTestWebModule extends AbstractSAPLTestWebModule {
}
